name: madison25flopy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - contextily
  - descartes
  - fiona
  - flopy
  - git
  - geopandas
  - geos
  - geojson
  - imageio
  - jupyter
  - jupytext
  - jupyterlab
  - modflowapi
  - netcdf4
  - openpyxl
  - pip
  - pymetis
  - pytest
  - pyvista
  - pyyaml
  - rasterio
  - rasterstats
  - requests
  - rioxarray
  - rtree
  - statsmodels
  - uxarray
  - vtk
  - xarray
  - xugrid
  - xlrd
  # build dependencies
  - pkg-config
  - meson
  - ninja
  - gfortran
  - openmpi
  - libnetcdf
  - netcdf-fortran
  - petsc=3.20.5

